hostname: remove '-'
This allows using this configuration in a NixOS VM test.
Otherwise evaluating the test fails with:
  error: Cannot create machines out of (nixbitcoin-org)!
  All machines are referenced as python variables in the testing framework which will break the
  script when special characters are used.